---
- name: Create defined list of Docker networks
  docker_network:
    name: "{{ item.name }}"
    state: present
    appends: true
    driver: "{{ item.driver | default(omit) }}"
    driver_options: "{{ item.driver_options | default(omit) }}"
    ipam_options: "{{ item.ipam_options | default(omit) }}"
  with_items: "{{ bulk_docker_containers_network_list }}"
  become: true

- name: Start defined list of Docker containers
  docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    state: "{{ item.state | default('started') }}"
    env: "{{ item.env | default(omit) }}"
    capabilities: "{{ item.capabilities | default(omit) }}"
    dns_servers: "{{ item.dns_servers | default(omit) }}"
    hostname: "{{ item.hostname | default(omit) }}"
    init: "{{ item.init | default(omit) }}"
    labels: "{{ item.labels | default(omit) }}"
    network_mode: "{{ item.network_mode | default(omit) }}"
    networks: "{{ item.networks | default(omit) }}"
    purge_networks: "{{ item.purge_networks | default(omit) }}"
    published_ports: "{{ item.published_ports | default(omit) }}"
    restart_policy: "{{ item.restart_policy | default('unless-stopped') }}"
    volumes: "{{ item.volumes | default(omit) }}"
  with_items: "{{ bulk_docker_containers_list }}"
  become: true
